"""init

Revision ID: a597f3050d1e
Revises:
Create Date: 2026-05-18 00:34:21.142098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a597f3050d1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('numero_documento', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre_completo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profesion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_de_colegiatura', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('especialidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('servicio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleado_numero_documento'), 'empleado', ['numero_documento'], unique=False)
    op.create_table('leyenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hora_inicio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hora_fin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cargo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leyenda_sigla'), 'leyenda', ['sigla'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leyenda_sigla'), table_name='leyenda')
    op.drop_table('leyenda')
    op.drop_index(op.f('ix_empleado_numero_documento'), table_name='empleado')
    op.drop_table('empleado')
    # ### end Alembic commands ###
