"""empleados

Revision ID: ba5e124c0a54
Revises: 025ce4b85563
Create Date: 2026-05-17 23:57:10.059423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba5e124c0a54'
down_revision: Union[str, Sequence[str], None] = '025ce4b85563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('numero_documento', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre_completo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profesion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_de_colegiatura', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('especialidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('servicio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleado_numero_documento'), 'empleado', ['numero_documento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empleado_numero_documento'), table_name='empleado')
    op.drop_table('empleado')
    # ### end Alembic commands ###
