"""create leyenda table

Revision ID: cba1b5eedb67
Revises:
Create Date: 2026-05-16 12:27:43.272542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cba1b5eedb67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leyenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('hora_inicio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hora_fin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cargo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leyenda_nombre'), 'leyenda', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leyenda_nombre'), table_name='leyenda')
    op.drop_table('leyenda')
    # ### end Alembic commands ###
